### ISSUE TITLE
Need flutter 2.0 support  (Null safety)

### ISSUE THREAD

**Issue by pmathulan** [florent37/Flutter-AssetsAudioPlayer#486]
Need flutter 2.0 support  (Null safety)
My Flutter version is: 2.0.1 • channel stable 

I got the following error:

Because assets_audio_player >=2.0.14 depends on path_provider ^1.6.27 which depends on path_provider_windows ^0.0.4, assets_audio_player >=2.0.14 requires path_provider_windows ^0.0.4.
And because shared_preferences_windows 2.0.0 depends on path_provider_windows ^2.0.0 and no versions of shared_preferences_windows match >2.0.0 <3.0.0, assets_audio_player >=2.0.14 is incompatible with shared_preferences_windows ^2.0.0.
And because shared_preferences 2.0.3 depends on shared_preferences_windows ^2.0.0 and no versions of shared_preferences match >2.0.3 <3.0.0, assets_audio_player >=2.0.14 is incompatible with shared_preferences ^2.0.3.

**Comment by nohli** [comment]
To make it work right now you can add this to your pubspec.yaml:

```
dependency_overrides:
  path_provider: ^2.0.1
  uuid: ^3.0.1
```

Maybe you won't need the uuid part.

**Comment by pmathulan** [comment]
Dear @nohli,
Still, I got the following error.

Because assets_audio_player >=2.0.14 depends on path_provider ^1.6.27 and my_app depends on path_provider ^2.0.1, assets_audio_player >=2.0.14 is forbidden.

**Comment by nohli** [comment]
@pmathulan please copy paste your pubspec.yaml here (at best in a code block)

**Comment by pmathulan** [comment]
@nohli here is the pubspec.yaml

`version: 2.0.0+2025

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.11.0+1
  firebase_crashlytics: ^1.0.0
  firebase_core: ^1.0.0
  url_launcher: ^6.0.2
  shared_preferences: ^2.0.3
  flutter_spinkit: ^5.0.0
  path_provider: ^2.0.1
  uuid: ^3.0.1
  assets_audio_player: ^2.0.14`

**Comment by nohli** [comment]
So you didn't add the mentioned override?

Please wrap code in ```

**Comment by pmathulan** [comment]
@nohli now it's working with a warning.

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^0.11.0+1
  firebase_crashlytics: ^1.0.0
  firebase_core: ^1.0.0
  url_launcher: ^6.0.2
  shared_preferences: ^2.0.3
  flutter_spinkit: ^5.0.0
  assets_audio_player: ^2.0.14

dependency_overrides:
  path_provider: ^2.0.1
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Comment by vmeretin** [comment]
dependency_overrides is not a solution. 

From https://dart.dev/tools/pub/dependencies
> Warning: Using a dependency override involves some risk. For example, using an override to specify a version outside the range that the package claims to support, or using an override to specify a local copy of a package that has unexpected behaviors, may break your application.

Plugin needs in migration to Dart 2.12 for support sound null safety.

**Comment by kalismeras61** [comment]
@nohli, With my current work, I am extremely busy now. :( I will merge supporting Android API 30 this weekend and fix some other issues as well. If you start null-safety it will be very good for me.

Thanks.

**Comment by nohli** [comment]
Quick questions about the pubspec.yaml of the example app:

1. https://pub.dev/packages/flutter_audio_recorder isn't null safe and hasn't been updated for a long time - can we easily replace it?

2. https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/pubspec.yaml:
dio: 3.0.9 is without ^ - is this for a specific reason that is still valid, or can it be upgraded?

**Comment by kalismeras61** [comment]
@nohli , actually for first 1 it is only used example app. We can remove that ,also specific main file as well. 
2- Same thing, we can upgrade also dio.

**Comment by nohli** [comment]
@pmathulan I'm working full time. Hopefully, this weekend it can be done.

**Comment by pmathulan** [comment]
@nohli Ok, Thank you.

**Comment by samrat19** [comment]
any update for the null safety release?

**Comment by DomingoMG** [comment]
I am waiting to receive the update for null security.

**Comment by nohli** [comment]
https://github.com/kossnocorp/etiquette

**Comment by kalismeras61** [comment]
@nohli Unfortunately, people are very impatient, we want to take time in our current jobs and benefit people. Unfortunately, they don't understand the importance of this. Thanks for the effort!

**Comment by nohli** [comment]
Try it:

```
  assets_audio_player:
    git:
      url: https://github.com/nohli/Flutter-AssetsAudioPlayer
      ref: migrate-to-nnbd
```
