### ISSUE TITLE
Duplicate Class Error

### ISSUE THREAD

**Issue by HadenHiles** [florent37/Flutter-AssetsAudioPlayer#679]
**Issue:**
I'm getting a duplicate class error for com.google.android.exoplayer when trying to build a project after upgrading to latest **flutter:stable 10.2.4**.

**Platform + version**
`Pixel XL (mobile) • Android 10 (API 29)`

**Gradle Version**
`7.2`

**flutter doctor -v:**
```
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.556], locale en-CA)
    • Flutter version 2.10.4 at C:\Users\haden\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (2 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\haden\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7179

[✓] VS Code (version 1.65.2)
    • VS Code at C:\Users\haden\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[✓] Connected device (4 available)
    • Pixel XL (mobile) • HT72N0200904 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows      • windows-x64    • Microsoft Windows [Version 10.0.22000.556]
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 96.0.4664.93
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 99.0.1150.39

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Error log:**

```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.DownloadNotificationHelper found in modules jetified-exoplayer-core-2.17.0-runtime (com.google.android.exoplayer:exoplayer-core:2.17.0) and jetified-exoplayer-ui-2.15.0-runtime (com.google.android.exoplayer:exoplayer-ui:2.15.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

Let me know if you need me to setup a project to reproduce.

**Comment by HadenHiles** [comment]
I tried making a copy of the package and updating the exoplayer version to 2.17.0, as well as removing the exoplayer implementations altogether but that only caused more unresolved reference errors. Just hoping I'm not the only one experiencing this issue 😓 

Thanks in advance for any suggestions or solutions!

**Comment by ahanson24** [comment]
I'm having the same issue as well.

**Comment by ahanson24** [comment]
When I get done with work I'll post my flutter doctor and error log

**Comment by kalismeras61** [comment]
@HadenHiles can you share, your pubspec.yaml file? 
I have upgraded flutter version with latest one. I don't have same issue.

**Comment by HadenHiles** [comment]
Certainly I'll put my pubspec.yaml below and I'll try running the example project tomorrow. There's probably another package I'm using that also depends on exoplayer for android but I wasn't able to confirm that's the case.

I appreciate your help 😄 

**pubspec.yaml**
```
name: g7trailapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.2
  firebase_core: ^1.10.0
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.10
  firebase_storage: ^10.2.9
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.10
  firebase_remote_config: ^2.0.2
  package_info: ^2.0.2
  get_it: ^7.2.0 
  introduction_screen: ^3.0.0
  workmanager: ^0.4.1
  flutter_local_notifications: ^9.3.2
  ci_connectivity: ^1.1.0
  flutter_beacon: 
    path: ./flutter_beacon-0.5.1-g7/
  http: ^0.13.4
  timezone: ^0.8.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  global_configuration: ^2.0.0-nullsafety.1 
  google_sign_in: ^5.1.1
  the_apple_sign_in: ^1.1.1
  flutter_signin_button: ^2.0.0
  password_strength: ^0.2.0 
  flutter_settings_ui: ^2.0.1
  url_launcher: ^6.0.17
  sliding_up_panel: ^2.0.0+1
  overlay_support: ^1.2.1
  auto_size_text: ^3.0.0
  vibration: ^1.7.4-nullsafety.0 
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  simple_animations: ^4.0.1
  google_maps_flutter: ^2.1.1
  flutter_html: ^2.2.1
  # assets_audio_player: ^3.0.4+1 # TODO: uncomment this when assets_audio_player duplicate class bug is resolved
  audio_video_progress_bar: ^0.10.0
  flutter_tts: ^3.3.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/destinations/
    - assets/fonts/
    - assets/fonts/LouisGeorgeCafe/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LGCafe
      fonts:
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafe.ttf
          weight: 400
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeItalic.ttf
          style: italic
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeBold.ttf
          weight: 800
        - asset: assets/fonts/LouisGeorgeCafe/LouisGeorgeCafeLight.ttf
          weight: 200

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
