### ISSUE TITLE
Execution failed for task ':assets_audio_player_web:compileDebugKotlin'. > Error while evaluating property 'compilerOptions.jvmTarget' of task ':assets_audio_player_web:compileDebugKotlin'.    > Failed to calculate the value of property 'jvmTarget'.       > Unknown Kotlin JVM target: 21

### ISSUE THREAD

**Issue by armagangok** [florent37/Flutter-AssetsAudioPlayer#854]
**Flutter Version**
3.24.4

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

* What went wrong:
Execution failed for task ':assets_audio_player_web:compileDebugKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':assets_audio_player_web:compileDebugKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 21

**Comment by pyaehein** [comment]
+1

**Comment by ElemenzaDev** [comment]
+

**Comment by joveptesg** [comment]
+1

**Comment by a-rfl** [comment]
+1

**Comment by SigosAmigo** [comment]
+1

**Comment by Rupakpoddar** [comment]
**Note:** This change may not work for Flutter web platforms.

Try changing the following in `pubspec.yaml`:

**Before:**
```
dependencies:
  assets_audio_player: ^3.1.1
```

**After:**
```
dependencies:
  assets_audio_player:
    git:
      url: https://github.com/Rupakpoddar/Flutter-AssetsAudioPlayer
```

**Comment by Rupakpoddar** [comment]
**Note:** This change will not work for Flutter web platforms.

Try changing the following in `pubspec.yaml`:

**Before:**
```
dependencies:
  assets_audio_player: ^3.1.1
```

**After:**
```
dependencies:
  assets_audio_player:
    git:
      url: https://github.com/Rupakpoddar/Flutter-AssetsAudioPlayer
```

**Comment by vlowe85** [comment]
+1

Any workaround?

**Comment by Christiaan-Mathu** [comment]
I had the same issue, and can confirm that setting the dependency to @Rupakpoddar's branch does work as a temporary fix.

> **Note:** This change will not work for Flutter web platforms.
> 
> Try changing the following in `pubspec.yaml`:
> 
> **Before:**
> 
> ```
> dependencies:
>   assets_audio_player: ^3.1.1
> ```
> 
> **After:**
> 
> ```
> dependencies:
>   assets_audio_player:
>     git:
>       url: https://github.com/Rupakpoddar/Flutter-AssetsAudioPlayer
> ```

**EDIT**

This should be fixed in https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/858, just waiting for new release, but as temporary fix can point to the repo branch


```
dependencies:
  # Can be changed back once a new version is released after 3.1.1
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer
 ```
